services:
  - type: web
    name: shopgenie-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium chromium-driver && \
      pip install -r requirements.txt
    startCommand: python scrapers_api.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
