services:
  - type: web
    name: shopgenie-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python scrapers_api.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
